/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PreAlert {
  created_at: Generated<Timestamp | null>;
  event_hash: string;
  id: Generated<number>;
  json_data: Json;
  status: Generated<string | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface PreAlertSource {
  pre_alert_id: number;
  source_id: number;
}

export interface Source {
  clean_text: string | null;
  content_hash: string | null;
  fetched_at: Generated<Timestamp | null>;
  id: Generated<number>;
  medium: string | null;
  metadata: Json | null;
  published_at: Timestamp | null;
  raw_content: string | null;
  title: string | null;
  url: string;
}

export interface DB {
  pre_alert: PreAlert;
  pre_alert_source: PreAlertSource;
  source: Source;
}
